# Generated by cucumber-sinatra. (2014-09-22 19:09:11 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'chitter.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app, _ = Rack::Builder.parse_file(File.expand_path('../../../config.ru', __FILE__))


class ChitterWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ChitterWorld.new
end
